plugins {
    id 'java'
    id 'idea'
}

group = 'co.uk.softwarecraftsmanship'
version = '1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation libs.junit.jupiter
    testImplementation libs.hamcrest
    testRuntimeOnly libs.junit.platform.launcher
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}
